
const perguntas = [
    { pergunta: "Quanto é 3 + 4?", resposta: "7" },
    { pergunta: "Qual é a capital do Brasil?", resposta: "Brasília" },
    { pergunta: "Quanto é 9 - 2?", resposta: "7" },
    { pergunta: "Qual o plural de 'animal'?", resposta: "animais" },
    { pergunta: "Quantos dias tem uma semana?", resposta: "7" },
    { pergunta: "Quanto é 5 x 2?", resposta: "10" },
    { pergunta: "Quanto é 10 ÷ 2?", resposta: "5" },
    { pergunta: "Que cor é formada por azul + amarelo?", resposta: "verde" },
    { pergunta: "Quanto é 6 + 6?", resposta: "12" },
    { pergunta: "Qual é o menor número primo?", resposta: "2" },
    { pergunta: "Quantas pernas tem uma aranha?", resposta: "8" },
    { pergunta: "Quantas letras tem a palavra 'coração'?", resposta: "7" },
    { pergunta: "Qual planeta é conhecido como planeta vermelho?", resposta: "Marte" },
    { pergunta: "Quanto é 3 x 3?", resposta: "9" },
    { pergunta: "Quantos segundos tem um minuto?", resposta: "60" },
    { pergunta: "Quanto é 15 - 7?", resposta: "8" },
    { pergunta: "Qual o antônimo de 'feliz'?", resposta: "triste" },
    { pergunta: "Qual é a primeira letra do alfabeto?", resposta: "A" },
    { pergunta: "Qual o resultado de 7 + 8?", resposta: "15" },
    { pergunta: "Qual é o nome do nosso planeta?", resposta: "Terra" },
    { pergunta: "Quantos meses tem um ano?", resposta: "12" },
    { pergunta: "Qual é a cor do céu sem nuvens?", resposta: "azul" },
    { pergunta: "Quanto é 2 x 4?", resposta: "8" },
    { pergunta: "Quantas patas tem um cachorro?", resposta: "4" },
    { pergunta: "Quanto é 20 ÷ 4?", resposta: "5" },
    { pergunta: "Qual é o oposto de 'noite'?", resposta: "dia" },
    { pergunta: "Quantos dedos tem uma mão?", resposta: "5" },
    { pergunta: "Qual é o resultado de 9 + 1?", resposta: "10" },
    { pergunta: "Qual é a cor da banana madura?", resposta: "amarela" },
    { pergunta: "Quanto é 12 ÷ 3?", resposta: "4" }
];
