const perguntas = [
    { pergunta: "Quanto é 5 + 3?", resposta: "8", opcoes: ["6", "8", "9"] },
    { pergunta: "Qual é a capital do Brasil?", resposta: "Brasília", opcoes: ["Rio", "Brasília", "São Paulo"] },
    { pergunta: "Quanto é 9 - 4?", resposta: "5", opcoes: ["4", "5", "6"] },
    { pergunta: "Quem descobriu o Brasil?", resposta: "Pedro Álvares Cabral", opcoes: ["Dom Pedro", "Pedro Álvares Cabral", "Tiradentes"] },
    { pergunta: "Quanto é 6 x 2?", resposta: "12", opcoes: ["12", "10", "14"] },
    { pergunta: "Quantos estados tem o Brasil?", resposta: "26", opcoes: ["26", "27", "25"] },
    { pergunta: "Qual é o maior planeta do Sistema Solar?", resposta: "Júpiter", opcoes: ["Terra", "Marte", "Júpiter"] },
    { pergunta: "Quanto é 7 + 6?", resposta: "13", opcoes: ["12", "13", "14"] },
    { pergunta: "Em que continente está o Egito?", resposta: "África", opcoes: ["Ásia", "Europa", "África"] },
    { pergunta: "Quanto é 4 x 3?", resposta: "12", opcoes: ["8", "12", "16"] },
    { pergunta: "Qual é o menor país do mundo?", resposta: "Vaticano", opcoes: ["Mônaco", "Vaticano", "Malta"] },
    { pergunta: "Quanto é 15 ÷ 3?", resposta: "5", opcoes: ["4", "5", "6"] },
    { pergunta: "Qual é a cor do céu em um dia claro?", resposta: "Azul", opcoes: ["Azul", "Cinza", "Verde"] },
    { pergunta: "Quanto é 10 + 5?", resposta: "15", opcoes: ["14", "15", "16"] },
    { pergunta: "Qual animal é conhecido como rei da selva?", resposta: "Leão", opcoes: ["Leão", "Tigre", "Elefante"] },
    { pergunta: "Quanto é 6 + 7?", resposta: "13", opcoes: ["12", "13", "14"] },
    { pergunta: "Qual é o símbolo químico da água?", resposta: "H2O", opcoes: ["H2O", "O2", "CO2"] },
    { pergunta: "Quanto é 9 x 2?", resposta: "18", opcoes: ["16", "18", "20"] },
    { pergunta: "Qual planeta é conhecido como planeta vermelho?", resposta: "Marte", opcoes: ["Júpiter", "Marte", "Saturno"] },
    { pergunta: "Quanto é 20 - 4?", resposta: "16", opcoes: ["15", "16", "17"] },
    { pergunta: "Qual é o maior oceano da Terra?", resposta: "Pacífico", opcoes: ["Atlântico", "Índico", "Pacífico"] },
    { pergunta: "Quanto é 11 + 9?", resposta: "20", opcoes: ["19", "20", "21"] },
    { pergunta: "Qual animal põe ovos?", resposta: "Galinha", opcoes: ["Cachorro", "Galinha", "Gato"] },
    { pergunta: "Quanto é 14 ÷ 2?", resposta: "7", opcoes: ["6", "7", "8"] },
    { pergunta: "Qual é o nome do nosso satélite natural?", resposta: "Lua", opcoes: ["Sol", "Lua", "Terra"] },
    { pergunta: "Quanto é 18 - 9?", resposta: "9", opcoes: ["8", "9", "10"] },
    { pergunta: "Quem pintou a Mona Lisa?", resposta: "Leonardo da Vinci", opcoes: ["Van Gogh", "Picasso", "Leonardo da Vinci"] },
    { pergunta: "Quanto é 8 x 3?", resposta: "24", opcoes: ["21", "24", "27"] },
    { pergunta: "Qual o nome do presidente do Brasil em 2023?", resposta: "Lula", opcoes: ["Lula", "Bolsonaro", "Dilma"] },
    { pergunta: "Quanto é 12 + 7?", resposta: "19", opcoes: ["18", "19", "20"] }
];