
const perguntas = [
    { pergunta: "Quanto é 5 + 3?", resposta: "8", opcoes: ["6", "8", "9"] },
    { pergunta: "Qual é a capital do Brasil?", resposta: "Brasília", opcoes: ["Rio", "Brasília", "São Paulo"] },
    { pergunta: "Quanto é 9 - 4?", resposta: "5", opcoes: ["4", "5", "6"] },
    { pergunta: "Quem descobriu o Brasil?", resposta: "Pedro Álvares Cabral", opcoes: ["Dom Pedro", "Pedro Álvares Cabral", "Tiradentes"] },
    { pergunta: "Quanto é 6 x 2?", resposta: "12", opcoes: ["12", "10", "14"] },
    { pergunta: "Quantos dias tem uma semana?", resposta: "7", opcoes: ["5", "6", "7"] },
    { pergunta: "Qual o nome do planeta que vivemos?", resposta: "Terra", opcoes: ["Marte", "Terra", "Júpiter"] },
    { pergunta: "Quanto é 10 ÷ 2?", resposta: "5", opcoes: ["4", "5", "6"] },
    { pergunta: "Que cor se forma ao misturar azul e amarelo?", resposta: "Verde", opcoes: ["Roxo", "Laranja", "Verde"] },
    { pergunta: "Quantas patas tem um cachorro?", resposta: "4", opcoes: ["2", "3", "4"] },
    { pergunta: "Qual o contrário de dia?", resposta: "Noite", opcoes: ["Sol", "Noite", "Tarde"] },
    { pergunta: "Quanto é 3 x 4?", resposta: "12", opcoes: ["9", "12", "13"] },
    { pergunta: "Quantas letras tem a palavra 'amor'?", resposta: "4", opcoes: ["3", "4", "5"] },
    { pergunta: "Quem é o autor de 'O Sítio do Picapau Amarelo'?", resposta: "Monteiro Lobato", opcoes: ["Machado", "Monteiro Lobato", "Alencar"] },
    { pergunta: "Quanto é 7 + 2?", resposta: "9", opcoes: ["8", "9", "10"] },
    { pergunta: "Quantos meses tem um ano?", resposta: "12", opcoes: ["10", "11", "12"] },
    { pergunta: "Qual animal mia?", resposta: "Gato", opcoes: ["Cachorro", "Gato", "Pássaro"] },
    { pergunta: "Qual o maior órgão do corpo humano?", resposta: "Pele", opcoes: ["Fígado", "Pele", "Coração"] },
    { pergunta: "Quanto é 20 - 10?", resposta: "10", opcoes: ["10", "5", "15"] },
    { pergunta: "Qual o nome do nosso satélite natural?", resposta: "Lua", opcoes: ["Sol", "Lua", "Terra"] },
    { pergunta: "Qual é o plural de 'papel'?", resposta: "Papeis", opcoes: ["Papels", "Papeis", "Papeus"] },
    { pergunta: "O que usamos para ver?", resposta: "Olhos", opcoes: ["Mãos", "Olhos", "Pés"] },
    { pergunta: "Qual é a estação mais quente do ano?", resposta: "Verão", opcoes: ["Inverno", "Verão", "Outono"] },
    { pergunta: "Quanto é 8 ÷ 4?", resposta: "2", opcoes: ["2", "3", "4"] },
    { pergunta: "Qual o nome da rainha dos insetos?", resposta: "Abelha Rainha", opcoes: ["Formiga", "Abelha Rainha", "Joaninha"] },
    { pergunta: "Quanto é 7 x 2?", resposta: "14", opcoes: ["12", "13", "14"] },
    { pergunta: "Qual é a cor do céu em um dia limpo?", resposta: "Azul", opcoes: ["Azul", "Verde", "Branco"] },
    { pergunta: "Quanto é 15 + 5?", resposta: "20", opcoes: ["18", "20", "22"] },
    { pergunta: "O que usamos para escrever?", resposta: "Lápis", opcoes: ["Borracha", "Lápis", "Régua"] },
    { pergunta: "Qual o número depois do 29?", resposta: "30", opcoes: ["29", "30", "31"] }
];
